### ISSUE TITLE
Vou contar para sua mãe

### ISSUE THREAD

**Issue by ppamorim** [gpedro/clipboard-app#1]
A xinela vai estralhar

**Comment by gpedro** [comment]
irei aproveitar a issue para explicar as motivações deste aplicativo.

Estou cursando S.I (8 semestre) na Universidade Cuiabá. E a UNIC é uma das universidades do Grupo Kroton (só por isso já sabe que é uma bosta). Até semestre passado, o tal do "TCC" era para ser um artigo, dai nesse semestre voltou para TCC normal e agora tenho que desenvolve-lo em um bimestre porque além de voltarem o TCC, eu não ter prazo, ele ainda inventam que o TCC é online. Olha que delícia! Pequeniníssimo detalhe: A PORRA DO PORTAL QUE TÀ O TCC ONLINE, NEM PRONTO DIREITO ESTÁ! Até disponibilizarem essa porra, já está acabando o bimestre. Olha que lindeza! Não tenho tempo de viver e nem estudar!!!!!!!!!!!!!!!!!!!!!!!!!111111111111111

Esse aplicativo é o que resta.

agora irei voltar a tomar meu toddynho enquanto trabalho. cya~

![20150107parsa](https://cloud.githubusercontent.com/assets/2898638/10164239/70f99c34-6686-11e5-8921-f34a6e8cc48b.jpg)

**Comment by gabrielpaivadev** [comment]
AHHHH EU NÃO DEIXAVA!!!!!

**Comment by gpedro** [comment]
até você aqui, @gpgabrielpaiva !

**Comment by gabrielpaivadev** [comment]
Sou mais conhecido como "camper" do Github.

**Comment by renatorib** [comment]
@gpedro agora já sei o nome da sua universidade, qm sabe não mando um email com um link

**Comment by gpedro** [comment]
![](http://i.imgur.com/Y1b6eUt.gif)

**Comment by ppamorim** [comment]
por isso q mandei a faculdade pro inferno :+1:

**Comment by renatorib** [comment]
@ppamorim também fiz isso hauehuae

**Comment by gabrielpaivadev** [comment]
Por isso eu nunca fiz faculdade, temos um vencedor?

**Comment by gpedro** [comment]
https://www.youtube.com/watch?v=wtBvZLOHDRQ
