### ISSUE TITLE
Shame

### ISSUE THREAD

**Issue by ppamorim** [gpedro/clipboard-app#2]
so o fato de vc ter feito uma webview é motivo para vc ser estupriado por uma lhama.

**Comment by gpedro** [comment]
para de ser hater, coleginha. Por que você mesmo não cria um `clipboard-android-app`? (((((((((((((((: é uma boa exemplificação de comparação de código nativo e "híbrido"
![untitled](https://cloud.githubusercontent.com/assets/2898638/10175137/51f87a28-66bb-11e5-9786-8110123bd6eb.png)

**Comment by gpedro** [comment]
@ppamorim que tal?

**Comment by gabrielpaivadev** [comment]
AIUSHSAIUHSAIUAHSIUAHS TURN DOWN FOR WHAT

**Comment by ppamorim** [comment]
jesus n vai te perdoar

**Comment by gpedro** [comment]
Vai aceitar o desafio?

**Comment by ppamorim** [comment]
@gpedro As novinha n deixa

**Comment by ppamorim** [comment]
![furacao-sandy-560x420](https://cloud.githubusercontent.com/assets/5521682/10192377/5830776e-6752-11e5-8af0-27a7bf5467be.jpg)

**Comment by gpedro** [comment]
suck my AWESOME app using WEBVIEW with Lhamas
![its_work](https://cloud.githubusercontent.com/assets/2898638/10298539/32ce5274-6bae-11e5-9ec7-a50bc653de30.jpg)

**Comment by gabrielpaivadev** [comment]
MITOU!!! kkkkkkkkkkkkkkkkkkkkkkkkkk
